import { readFileSync, writeFileSync } from 'node:fs';
const root = new URL('../', import.meta.url);
const courses = JSON.parse(readFileSync(new URL('data/courses.json', root), 'utf8'));
const questions = JSON.parse(readFileSync(new URL('data/questions.json', root), 'utf8')).filter(item => item.active);
const quote = value => `'${String(value).replaceAll("'", "''")}'`;
const lines = ['-- Generated by scripts/generate-seed.mjs. Review before applying. Existing rows are preserved.', 'begin;'];
for (const course of courses) lines.push(`insert into public.v1_course_settings(course_id,question_count,pass_score,certificate_requirement) values(${quote(course.id)},${course.questionCount},${course.passScore},${quote(course.certificateRequirement)}) on conflict (course_id) do nothing;`);
for (const course of courses) for (const item of course.practicalItems) lines.push(`insert into public.v1_practical_items(course_id,item_id) values(${quote(course.id)},${quote(item.id)}) on conflict do nothing;`);
for (const question of questions) lines.push(`insert into public.v1_question_keys(id,course_id,correct_answer) values(${quote(question.id)},${quote(question.courseId)},${question.correctAnswer}) on conflict (id) do nothing;`);
lines.push(`insert into public.v1_quiz_attempts(id,user_id,course_id,question_ids,answers,score,passed,source,completed_at)
select md5('serveup-v1:' || progress.user_id::text || ':' || progress.course_id)::uuid,
       progress.user_id, mapping.v1_course_id, array[]::text[], '{}'::jsonb,
       greatest(0,least(100,coalesce(progress.score,0))), coalesce(progress.score,0) >= 80, 'legacy', coalesce(progress.completed_at,progress.updated_at,now())
from public.course_progress progress
join (values
  ('restaurant-basics','restaurant-orientation'),
  ('food-safety','hygiene-food-safety'),
  ('customer-service','guest-service-basics'),
  ('japanese-hospitality','guest-service-basics')
) as mapping(legacy_course_id,v1_course_id) on mapping.legacy_course_id = progress.course_id
on conflict (id) do nothing;`);
lines.push('commit;', '');
writeFileSync(new URL('migrations/002_serveup_v1_seed.sql', root), lines.join('\n'));
console.log(`Generated seed for ${courses.length} courses, ${questions.length} answer keys.`);
